---
title: "About Me"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Brief Introduction and Academic Background

Hello, My name is Jyoti Lalitha Kumar. I am an International Student from Mumbai, India. I graduated with a B.S. in Biological Sciences with a Molecular, Cellular, and, Developmental Biology concentration and Minors in Genetics and Microbiology. 

## Academic Achievements:

I was involved in on-campus research during my undergraduate career. I was involved in a Protein Purification experiment in the department of Biochemistry and I was involved in Bioinformatic Analysis in the department of Genetics at NC State University. Both my experiments have led me to submit peer reviewed research papers.

## Professional Background

Internship at Hoganas Environment Solutions (Cary, NC): I was an intern at the Microbiology Lab during summer 2018. Here, I was first exposed to wet lab practices and was responsible for innoculating cultures, making stock solutions and performing regular tests to test our sample. 

North Carolina State University: I worked as a community Assisstant for the Dorms at NC State. 

